name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm install

    - name: Build frontend
      working-directory: frontend
      run: npm run build

    - name: Install Hugging Face CLI
      run: |
        python -m pip install --upgrade pip
        pip install huggingface_hub

    - name: Configure Hugging Face CLI
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        huggingface-cli login --token $HF_TOKEN

    - name: Deploy to Spaces
      env:
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
        SPACE_NAME: ${{ secrets.SPACE_NAME }}
      run: |
        huggingface-cli upload $HF_USERNAME/$SPACE_NAME . --repo-type=space
